// icons.module.ts
import { NgModule } from '@angular/core';
import { LucideAngularModule } from 'lucide-angular';
import { BookOpen, Briefcase, GraduationCap, Info, LogIn, Bell,
         LayoutGrid, Menu, ChevronDown, ChevronUp, User, BookOpenCheck, BookMarked,
         Award, Facebook, Instagram, MessageCircle, ArrowRight, LayoutDashboard,
         Linkedin, X, Shield, FileText, HelpCircle, UserPlus, CornerDownRight,
         Settings, LogOut, Undo2, Home, Target, TrendingUp, Users, BookOpenIcon,
         Share2, ExternalLink,  ClipboardCheck,
         CheckCircle, Quote, Lightbulb, Heart, MessageSquare, Search,
         Sparkles, MousePointerClick, Palette} from 'lucide-angular';

@NgModule({
  imports: [
    LucideAngularModule.pick({
      BookOpen,
      Briefcase,
      GraduationCap,
      Info,
      LogIn,
      Bell,
      User,
      ClipboardCheck,
      LayoutGrid,
      Menu,
      ChevronDown,
  ChevronUp,
      BookOpenCheck,
      BookMarked,
      Award,
      Facebook,
      Instagram,
      MessageCircle,
      BookOpenIcon,
      ArrowRight,
      LayoutDashboard,
      Linkedin,
      Search,
      X,
      Shield,
      FileText,
      HelpCircle,
      UserPlus,
      CornerDownRight,
      Settings,
      LogOut,
      Undo2,
      Home,
      Target,
      TrendingUp,
      Users,
      CheckCircle,
      Quote,
      Lightbulb,
      Heart,
      MessageSquare,
      Share2,
      ExternalLink,
      Sparkles,
      MousePointerClick,
      Palette
    })
  ],
  exports: [LucideAngularModule],
})
export class IconsModule {}
