// Central feature flag KEY definitions for the app.
// Values are the flag keys consumed by RemoteConfigFacadeService / backend config.

export const FEATURE_FLAGS = {
  ADMIN_CONSOLE: 'ADMIN_CONSOLE',
  RESUME_PORTAL: 'RESUME_PORTAL',
  RESUME_BUILDER: 'RESUME_BUILDER',
  JOB_TRACKING: 'JOB_TRACKING',
  JOB_INTERVIEWS: 'JOB_INTERVIEWS',
  JOB_CONTACTS: 'JOB_CONTACTS',
  SAVED_JOBS: 'SAVED_JOBS',
  // Legacy: codebase uses 'ALERTS' in access/feature models; keep the constant name but map to that key.
  JOB_ALERTS: 'ALERTS',
  JOB_INTEGRATIONS: 'JOB_INTEGRATIONS',
  COURSE_CENTRAL: 'COURSE_CENTRAL',
  LEARNING_PATHS: 'LEARNING_PATHS',
  LEARNING_PLAN: 'LEARNING_PLAN',
  CERT_TRACKING: 'CERT_TRACKING',
  DOCUMENTS: 'DOCUMENTS',
  IMPORT_EXPORT: 'IMPORT_EXPORT',
  PAYMENT_METHODS: 'PAYMENT_METHODS',
  SUPPORT_TICKETS: 'SUPPORT_TICKETS',
  USER_FEEDBACK: 'USER_FEEDBACK',
  PUBLIC_PROFILE: 'PUBLIC_PROFILE',
  SECURITY_2FA: 'SECURITY_2FA',
  USER_INTEGRATIONS: 'USER_INTEGRATIONS',
  SUBSCRIPTIONS: 'SUBSCRIPTIONS',
  COUPONS: 'COUPONS',
  AUDIT_LOGS: 'AUDIT_LOGS',
  ERROR_MONITORING: 'ERROR_MONITORING',
  JOB_SCHEDULER: 'JOB_SCHEDULER',
  INTEGRATIONS: 'INTEGRATIONS',
  ANNOUNCEMENTS: 'ANNOUNCEMENTS',
  RBAC_ADMIN: 'RBAC_ADMIN',
  ENTERPRISE_ONBOARDING: 'ENTERPRISE_ONBOARDING',
  USER_ACTIVITY: 'USER_ACTIVITY',
  ENTERPRISE_CONSOLE: 'ENTERPRISE_CONSOLE',

  // Reserved internal flag used to hide nav items whose routes are not implemented in this repo.
  // This should not be enabled in any environment.
  NAV_PLACEHOLDER: 'NAV_PLACEHOLDER'
} as const;
